name: release.yml
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    strategy:
      matrix:
        include:
          - os: windows-latest
            netrun: win-x64
            artifact: release
          - os: ubuntu-latest
            netrun: linux-x64
            artifact: release_linux
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: publish bbatool
        run: |
          dotnet publish ./bbaToolS5/bbaToolS5.csproj -o ./Release -r ${{ matrix.netrun }} -c Release

      - uses: actions/upload-artifact@v4
        with:
          path: ./Release
          name: "${{ matrix.artifact }}"
          overwrite: true


  release:
    name: release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v7
        with:
          name: release
          path: ./Release

      - uses: actions/download-artifact@v7
        with:
          name: release_linux
          path: ./Release_Linux

      - name: zip win
        run: |
          sudo apt install zip
          cd ./Release
          zip -r ../Release.zip .
          cd ../

      - name: linux
        run: |
          sudo apt install zip
          cd ./Release_Linux
          zip -r ../Release_Linux.zip .
          cd ../

      - name: Delete tag
        run: gh release delete nightly --cleanup-tag -y || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: softprops/action-gh-release@v2
        with:
          body: "latest code from master"
          prerelease: true
          files: |
            ./Release.zip
            ./Release_Linux.zip
          name: nightly
          tag_name: nightly
          fail_on_unmatched_files: true
          target_commitish: master
          generate_release_notes: false
          append_body: false
          make_latest: false